"""user_actions_history

Revision ID: 6d79bc22005b
Revises: f1275efe010c
Create Date: 2023-05-09 18:21:33.248554

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6d79bc22005b"
down_revision = "f1275efe010c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_actions_history",
        sa.Column("id", sa.UUID(), nullable=False, comment="Идентификатор записи"),
        sa.Column("user_id", sa.UUID(), nullable=False, comment="Идентификатор пользователя"),
        sa.Column(
            "action",
            sa.String(length=255),
            nullable=False,
            comment="Действие пользователя",
        ),
        sa.Column("ip", sa.String(length=45), nullable=False, comment="IP пользователя"),
        sa.Column(
            "device_info",
            sa.String(length=255),
            nullable=True,
            comment="Информация о устройстве",
        ),
        sa.Column("created", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_actions_history_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_actions_history")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_users_id"), ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_users_id"), type_="unique")

    op.drop_table("user_actions_history")
    # ### end Alembic commands ###
