Проверка наличия подписки
---
description: Endpoint для проверки наличия подписки у пользователя.
tags:
  - Сервис управления подписками.
parameters:
  - name: name
    in: path
    description: Название подписки
    required: true
    type: string
  - name: body
    description: Тело запроса должно содержать все необходимые для проверки подписки данные.
    in: body
    required: true
    schema:
      type: object
      required:
        - "user_id"
      properties:
        user_id:
          type: string
  - name: Authorization
    in: header
    description: В заголовке Authorization запроса должен присутствовать Access токен (Bearer <access_token>)
    required: true
    type: string
responses:
  200:
    description: Пользователь успешно проверил наличие подписки.
  400:
    description: Произошла ошибка при попытке проверить наличие подписки.
  415:
    description: Ошибка формата входных данных.
  422:
    description: Ошибка состава запроса.