"""create_user_table

Revision ID: f1275efe010c
Revises:
Create Date: 2023-05-09 18:19:12.987866

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f1275efe010c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False, comment="Идентификатор пользователя"),
        sa.Column("created", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column(
            "modified",
            sa.DateTime(),
            nullable=True,
            comment="Время изменения записи",
            onupdate=sa.DateTime(),
        ),
        sa.Column("login", sa.String(length=256), nullable=False, comment="Логин пользователя"),
        sa.Column(
            "email",
            sa.String(length=320),
            nullable=False,
            comment="Адрес электронной почты пользователя",
        ),
        sa.Column(
            "password_hash",
            sa.String(length=128),
            nullable=False,
            comment="Хэш пароля пользователя",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Признак активного пользователя",
        ),
        sa.Column(
            "is_verified",
            sa.Boolean(),
            nullable=False,
            comment="Признак верифицированного пользователя",
        ),
        sa.Column("is_admin", sa.Boolean(), nullable=False, comment="Признак администратора"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("id", name=op.f("uq_users_id")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_login"), ["login"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_login"))

    op.drop_table("users")
    # ### end Alembic commands ###
